import { NextRequest, NextResponse } from 'next/server'
import { createClient, createAdminClient } from '@/lib/supabase/server'
import { initializePayment } from '@/lib/paystack/client'
import type { GhanaRegion } from '@/types'

const DELIVERY_FEE = 20 // GHS

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { data: profile } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single()

    const { searchParams } = new URL(request.url)
    const page    = parseInt(searchParams.get('page') ?? '1')
    const limit   = parseInt(searchParams.get('limit') ?? '20')
    const status  = searchParams.get('status')
    const offset  = (page - 1) * limit

    let query = supabase
      .from('orders')
      .select(`
        *,
        buyer:users(*),
        vendor:vendor_profiles(id, business_name, logo_url),
        product:products(id, title, images, slug, price_ghs)
      `, { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1)

    if (status) {
      query = query.eq('status', status)
    }

    // Filter by role
    if (profile?.role === 'buyer') {
      query = query.eq('buyer_id', user.id)
    } else if (profile?.role === 'vendor') {
      // Find vendor profile
      const { data: vendorProfile } = await supabase
        .from('vendor_profiles')
        .select('id')
        .eq('user_id', user.id)
        .single()
      if (vendorProfile) {
        query = query.eq('vendor_id', vendorProfile.id)
      }
    }
    // Admin can see all

    const { data: orders, count, error } = await query

    if (error) throw error

    return NextResponse.json({
      data: orders,
      count,
      page,
      per_page: limit,
      total_pages: Math.ceil((count ?? 0) / limit),
    })
  } catch (err) {
    console.error('[GET /api/orders]', err)
    return NextResponse.json(
      { error: 'Failed to fetch orders' },
      { status: 500 },
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const {
      product_id,
      quantity = 1,
      delivery_address,
      delivery_region,
      buyer_notes,
    } = body as {
      product_id: string
      quantity: number
      delivery_address: string
      delivery_region: GhanaRegion
      buyer_notes?: string
    }

    if (!product_id || !delivery_address || !delivery_region) {
      return NextResponse.json(
        { error: 'product_id, delivery_address, and delivery_region are required' },
        { status: 400 },
      )
    }

    // Fetch product
    const { data: product, error: productError } = await supabase
      .from('products')
      .select('*, vendor:vendor_profiles(id, user_id)')
      .eq('id', product_id)
      .single()

    if (productError || !product) {
      return NextResponse.json({ error: 'Product not found' }, { status: 404 })
    }

    if (product.status !== 'approved') {
      return NextResponse.json({ error: 'Product is not available' }, { status: 400 })
    }

    if (product.stock_quantity < quantity) {
      return NextResponse.json({ error: 'Insufficient stock' }, { status: 400 })
    }

    if (product.minimum_order && quantity < product.minimum_order) {
      return NextResponse.json(
        { error: `Minimum order quantity is ${product.minimum_order}` },
        { status: 400 },
      )
    }

    const vendorProfile = product.vendor as { id: string; user_id: string } | null
    if (!vendorProfile) {
      return NextResponse.json({ error: 'Vendor not found' }, { status: 404 })
    }

    // Fetch buyer info
    const { data: buyer } = await supabase
      .from('users')
      .select('email, full_name')
      .eq('id', user.id)
      .single()

    if (!buyer) {
      return NextResponse.json({ error: 'Buyer profile not found' }, { status: 404 })
    }

    // Calculate pricing
    const unit_price  = product.price_ghs
    const subtotal    = unit_price * quantity
    const delivery_fee = DELIVERY_FEE
    const total_amount = subtotal + delivery_fee

    // Create order (reference auto-generated by Postgres trigger)
    const adminSupabase = await createAdminClient()
    const { data: order, error: orderError } = await adminSupabase
      .from('orders')
      .insert({
        buyer_id:          user.id,
        vendor_id:         vendorProfile.id,
        product_id:        product.id,
        quantity,
        unit_price,
        subtotal,
        delivery_fee,
        total_amount,
        status:            'pending',
        delivery_address,
        delivery_region,
        buyer_notes:       buyer_notes || null,
      })
      .select()
      .single()

    if (orderError || !order) {
      console.error('[POST /api/orders] Order insert error:', orderError)
      return NextResponse.json({ error: 'Failed to create order' }, { status: 500 })
    }

    // Initialize Paystack payment
    const payment = await initializePayment({
      email:  buyer.email,
      amount: total_amount * 100, // convert GHS to pesewas
      metadata: {
        order_id:   order.id,
        buyer_id:   user.id,
        vendor_id:  vendorProfile.id,
        reference:  order.reference,
      },
      callback_url: `${process.env.NEXT_PUBLIC_APP_URL ?? 'https://marketplace.swkghana.org'}/buyer/orders/${order.id}?payment=success`,
    })

    // Store Paystack reference
    await adminSupabase
      .from('orders')
      .update({ paystack_reference: payment.reference })
      .eq('id', order.id)

    return NextResponse.json(
      {
        data: { ...order, paystack_reference: payment.reference },
        payment_url: payment.authorization_url,
        message: 'Order created successfully',
      },
      { status: 201 },
    )
  } catch (err) {
    console.error('[POST /api/orders]', err)
    return NextResponse.json(
      { error: 'Failed to create order' },
      { status: 500 },
    )
  }
}
